/*
 * Copyright (c) 2026 Noverse (Nohuto). All rights reserved.
 * Proprietary and confidential. Unauthorized copying or redistribution is strictly prohibited.
 */

#pragma once

#include "common.h"

namespace nvcli
{
    void PrintGpuHeader(NvU32 index, NvPhysicalGpuHandle handle);
    void PrintBusInfo(NvPhysicalGpuHandle handle);
    void PrintVbiosInfo(NvPhysicalGpuHandle handle);
    void PrintMemoryInfo(NvPhysicalGpuHandle handle);
    void PrintBarInfo(NvPhysicalGpuHandle handle);
    void PrintPowerInfo(NvPhysicalGpuHandle handle);
    void PrintPstateInfo(NvPhysicalGpuHandle handle);
    void PrintUtilizationInfo(NvPhysicalGpuHandle handle);
    void PrintClockInfo(NvPhysicalGpuHandle handle);
    void PrintCoolerInfo(NvPhysicalGpuHandle handle);
    void PrintHexBytes(const NvU8 *data, NvU32 size);
    double TimingRefreshHz(const NV_TIMING &timing);
    const char *GsyncConnectorName(NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR connector);
    bool GetGsyncHandleByIndex(NvU32 index, NvGSyncDeviceHandle *outHandle);
    const char *HdmiFrlRateName(NV_HDMI_FRL_RATE rate);

    int CmdInfo();
    int CmdDisplayIds(int argc, char **argv);
    int CmdDisplayEdid(int argc, char **argv);
    int CmdDisplayTiming(int argc, char **argv);
    int CmdDisplayList();
    int CmdDisplayGet(int argc, char **argv);
    int CmdDisplaySet(int argc, char **argv);
    int CmdDisplayCustom(int argc, char **argv);
    int CmdDisplayMonitorCaps(int argc, char **argv);
    int CmdDisplayMonitorColorCaps(int argc, char **argv);
    int CmdDisplayScaling(int argc, char **argv);
    int CmdDisplayScalingOverride(int argc, char **argv);
    int CmdDisplayViewport(int argc, char **argv);
    int CmdDisplayFeature(int argc, char **argv);
    int CmdDisplayWideColor(int argc, char **argv);
    int CmdDisplayBpc(int argc, char **argv);
    int CmdDisplayBlanking(int argc, char **argv);
    int CmdDisplayHdr(int argc, char **argv);
    int CmdDisplayIdByName(int argc, char **argv);
    int CmdDisplayGdiPrimary();
    int CmdDisplayHandleFromId(int argc, char **argv);
    int CmdDisplayIdFromHandle(int argc, char **argv);
    int CmdMosaicCaps(int argc, char **argv);
    int CmdMosaicSupported(int argc, char **argv);
    int CmdMosaicCurrent();
    int CmdMosaicEnable(int argc, char **argv);
    int CmdMosaicDisplayCaps(int argc, char **argv);
    int CmdMosaic(int argc, char **argv);
    int CmdSliStatus();
    int CmdSliViews(int argc, char **argv);
    int CmdSli(int argc, char **argv);
    int CmdGsyncList();
    int CmdGsyncCaps(int argc, char **argv);
    int CmdGsyncTopology(int argc, char **argv);
    int CmdGsync(int argc, char **argv);
    int CmdDrsProfiles();
    int CmdDrsApps(int argc, char **argv);
    int CmdDrsSettings(int argc, char **argv);
    int CmdDrsSettingGet(int argc, char **argv);
    int CmdDrsSettingSet(int argc, char **argv);
    int CmdDrsProfileCreate(int argc, char **argv);
    int CmdDrsProfileDelete(int argc, char **argv);
    int CmdDrs(int argc, char **argv);
    int CmdVideoColorGet(NvDisplayHandle handle, bool useDefault);
    int CmdVideoColorGet(int argc, char **argv, bool useDefault);
    int CmdVideoColorSet(int argc, char **argv);
    int CmdVideo(int argc, char **argv);
    int CmdHdmiSupport(int argc, char **argv);
    int CmdHdmiHdcpDiag(int argc, char **argv);
    int CmdHdmiStereoModes(int argc, char **argv);
    int CmdHdmiStereoGet(int argc, char **argv);
    int CmdHdmiStereoSet(int argc, char **argv);
    int CmdHdmiAudioMute(int argc, char **argv);
    int CmdHdmi(int argc, char **argv);
    int CmdDpInfo(int argc, char **argv);
    int CmdDpSet(int argc, char **argv);
    int CmdDpDongle(int argc, char **argv);
    int CmdDpTopology(int argc, char **argv);
    int CmdDp(int argc, char **argv);
    int CmdGpuThermalSlowdown(int argc, char **argv);
    int CmdGpuThermalSlowdownSet(int argc, char **argv);
    int CmdGpuThermalSimGet(int argc, char **argv);
    int CmdGpuThermalSimSet(int argc, char **argv);
    int CmdGpuFanSet(int argc, char **argv);
    int CmdGpuFanRestore(int argc, char **argv);
    int CmdGpuPowerLimitGet(int argc, char **argv);
    int CmdGpuPowerLimitSet(int argc, char **argv);
    int CmdGpuPowerMonitor(int argc, char **argv);
    int CmdGpuPowerDevice(int argc, char **argv);
    int CmdGpuPowerCapping(int argc, char **argv);
    int CmdGpuPowerLeakage(int argc, char **argv);
    int CmdGpuEccStatus(int argc, char **argv);
    int CmdGpuEccErrors(int argc, char **argv);
    int CmdGpuEccConfig(int argc, char **argv);
    int CmdGpuEccReset(int argc, char **argv);
    int CmdGpuEcc(int argc, char **argv);
    int CmdGpuBoardManufacturing(int argc, char **argv);
    int CmdGpuBoard(int argc, char **argv);
    int CmdGpuPcieInfo(int argc, char **argv);
    int CmdGpuPcieErrors(int argc, char **argv);
    int CmdGpuPcieAer(int argc, char **argv);
    int CmdGpuPcieSwitchErrors(int argc, char **argv);
    int CmdGpuPcie(int argc, char **argv);
    int CmdGpuClientFan(int argc, char **argv);
    int CmdGpuClientIllum(int argc, char **argv);
    int CmdGpuClock(int argc, char **argv);
    int CmdGpuVoltage(int argc, char **argv);
    int CmdGpuVoltageControlSet(int argc, char **argv);
    int CmdGpuMemory(int argc, char **argv);
    int CmdGpuClocks(int argc, char **argv);
    int CmdGpuUtilization(int argc, char **argv);
    int CmdGpuPstate(int argc, char **argv);
    int CmdGpuBus(int argc, char **argv);
    int CmdGpuVbios(int argc, char **argv);
    int CmdGpuCooler(int argc, char **argv);
    int CmdGpuBar(int argc, char **argv);
    int CmdGpuPower(int argc, char **argv);
    int CmdGpuList();
    int CmdGpuThermal(int argc, char **argv);
    int CmdGpuPstates20(int argc, char **argv);
    int CmdGpuPstates20Private(int argc, char **argv);
    int CmdGpuPstates20PrivateSet(int argc, char **argv);
    int CmdGpuPstates20Set(int argc, char **argv);
    int CmdGpuVfTables(int argc, char **argv);
    int CmdGpuVfInject(int argc, char **argv);
    int CmdGpuVf(int argc, char **argv);
    int CmdGpuVpstatesInfo(int argc, char **argv);
    int CmdGpuVpstatesControl(int argc, char **argv);
    int CmdGpuVpstatesSet(int argc, char **argv);
    int CmdGpuVpstates(int argc, char **argv);
    int CmdGpuVfeVarsInfo(int argc, char **argv);
    int CmdGpuVfeVarsControl(int argc, char **argv);
    int CmdGpuVfeVarsSet(int argc, char **argv);
    int CmdGpuVfeVar(int argc, char **argv);
    int CmdGpuVfeEqusInfo(int argc, char **argv);
    int CmdGpuVfeEqusControl(int argc, char **argv);
    int CmdGpuVfeEqusSet(int argc, char **argv);
    int CmdGpuVfeEqu(int argc, char **argv);
    int CmdGpuPerfLimitsInfo(int argc, char **argv);
    int CmdGpuPerfLimitsStatus(int argc, char **argv);
    int CmdGpuPerfLimitsSet(int argc, char **argv);
    int CmdGpuPerfLimits(int argc, char **argv);
    int CmdGpu(int argc, char **argv);
    int CmdDisplay(int argc, char **argv);
    int CmdPcf(int argc, char **argv);
    int CmdD3d(int argc, char **argv);
    int CmdOgl(int argc, char **argv);
    int CmdVr(int argc, char **argv);
    int CmdStereo(int argc, char **argv);
    int CmdSys(int argc, char **argv);
}
